"""add_transaction_pin_and_login_count

Revision ID: 5b72bda8d0f3
Revises: b2c3d4e5f6a1
Create Date: 2026-03-14 20:52:01.237351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b72bda8d0f3'
down_revision: Union[str, None] = '81e65818b34d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('transaction_pin', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('login_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_count')
    op.drop_column('users', 'transaction_pin')
    # ### end Alembic commands ###
